export type CargoStatus = "yuklenecek" | "yolda" | "giden" | "devir" | "teslim" | "iptal"

export interface Cargo {
  id: string
  status: CargoStatus
  trackingNo: string
  pieces: number
  sender: string
  receiver: string
  from: string
  fromCity: string
  to: string
  toCity: string
  amount: number
  departureDate: string
  departureTime: string
  arrivalDate: string
  arrivalTime: string
  plate: string
}

export const statusLabels: Record<CargoStatus, string> = {
  yuklenecek: "Yuklenecek",
  yolda: "Yolda",
  giden: "Giden",
  devir: "Devir",
  teslim: "Teslim",
  iptal: "Iptal",
}

export const statusColors: Record<CargoStatus, { bg: string; text: string; border: string }> = {
  yuklenecek: { bg: "bg-white", text: "text-cargo-green", border: "border-cargo-green" },
  yolda: { bg: "bg-cargo-green", text: "text-white", border: "border-cargo-green" },
  giden: { bg: "bg-cargo-dark", text: "text-white", border: "border-cargo-dark" },
  devir: { bg: "bg-cargo-orange", text: "text-white", border: "border-cargo-orange" },
  teslim: { bg: "bg-emerald-600", text: "text-white", border: "border-emerald-600" },
  iptal: { bg: "bg-red-500", text: "text-white", border: "border-red-500" },
}

export const mockCargos: Cargo[] = [
  {
    id: "1",
    status: "yuklenecek",
    trackingNo: "203 515 071",
    pieces: 1,
    sender: "Sonmez Aktas",
    receiver: "Mehmet Deniz",
    from: "Izmit (Kocaeli) / Gebze",
    fromCity: "Gebze",
    to: "Usak / Banaz",
    toCity: "Banaz",
    amount: 300,
    departureDate: "14.02.2026",
    departureTime: "16:30",
    arrivalDate: "14.02.2026",
    arrivalTime: "22:30",
    plate: "50 DK 334",
  },
  {
    id: "2",
    status: "yuklenecek",
    trackingNo: "203 513 530",
    pieces: 1,
    sender: "Atess Elektronik Deniz Ekipmanlari Mgh San Ve Tic Ltd Sti\nEmre Yilmaz",
    receiver: "Huseyin Benli",
    from: "Izmit (Kocaeli) / Gebze",
    fromCity: "Gebze",
    to: "Mugla / Marmaris",
    toCity: "Marmaris",
    amount: 800,
    departureDate: "14.02.2026",
    departureTime: "13:45",
    arrivalDate: "14.02.2026",
    arrivalTime: "23:00",
    plate: "35 PK 511",
  },
  {
    id: "3",
    status: "yolda",
    trackingNo: "203 512 825",
    pieces: 2,
    sender: "Erdal Arik",
    receiver: "Atabik Aknazara",
    from: "Mugla / Fethiye",
    fromCity: "Fethiye",
    to: "Izmit (Kocaeli) / Gebze",
    toCity: "Gebze",
    amount: 1800,
    departureDate: "14.02.2026",
    departureTime: "11:00",
    arrivalDate: "14.02.2026",
    arrivalTime: "23:15",
    plate: "64 AN 674",
  },
  {
    id: "4",
    status: "devir",
    trackingNo: "203 510 719",
    pieces: 1,
    sender: "Suleyman Igneci",
    receiver: "Broche Tekstil",
    from: "Bursa / Osmangazi",
    fromCity: "Bursa",
    to: "Izmit (Kocaeli) / Gebze",
    toCity: "Gebze",
    amount: 400,
    departureDate: "13.02.2026",
    departureTime: "18:00",
    arrivalDate: "13.02.2026",
    arrivalTime: "19:15",
    plate: "39 AJ 025",
  },
  {
    id: "5",
    status: "giden",
    trackingNo: "203 515 186",
    pieces: 3,
    sender: "Bilal Yasa",
    receiver: "Adnan Yasar",
    from: "Izmit (Kocaeli) / Gebze",
    fromCity: "Gebze",
    to: "Bursa / Osmangazi",
    toCity: "Bursa",
    amount: 1000,
    departureDate: "14.02.2026",
    departureTime: "16:15",
    arrivalDate: "14.02.2026",
    arrivalTime: "17:30",
    plate: "34 TT 842",
  },
  {
    id: "6",
    status: "giden",
    trackingNo: "203 515 118",
    pieces: 1,
    sender: "Yuksel Marazer",
    receiver: "Arif Sonmez",
    from: "Izmit (Kocaeli) / Gebze",
    fromCity: "Gebze",
    to: "Balkesir / Bandirma",
    toCity: "Bandirma",
    amount: 300,
    departureDate: "14.02.2026",
    departureTime: "17:45",
    arrivalDate: "14.02.2026",
    arrivalTime: "20:30",
    plate: "10 AOJ 665",
  },
  {
    id: "7",
    status: "giden",
    trackingNo: "203 514 771",
    pieces: 1,
    sender: "Muhammet Tamtas",
    receiver: "Hasan Demircioglu",
    from: "Izmit (Kocaeli) / Gebze",
    fromCity: "Gebze",
    to: "Balkesir / Edremit",
    toCity: "Edremit",
    amount: 400,
    departureDate: "14.02.2026",
    departureTime: "15:00",
    arrivalDate: "14.02.2026",
    arrivalTime: "19:15",
    plate: "34 ERD 456",
  },
  {
    id: "8",
    status: "giden",
    trackingNo: "203 514 588",
    pieces: 1,
    sender: "Ahmet Akkurt",
    receiver: "Bek Denizcilik\nMuhsin Altintas",
    from: "Izmit (Kocaeli) / Gebze",
    fromCity: "Gebze",
    to: "Balkesir / Bandirma",
    toCity: "Bandirma",
    amount: 400,
    departureDate: "14.02.2026",
    departureTime: "15:15",
    arrivalDate: "14.02.2026",
    arrivalTime: "18:15",
    plate: "41 TT 422",
  },
  {
    id: "9",
    status: "giden",
    trackingNo: "203 513 815",
    pieces: 1,
    sender: "Bma Teknoloji AS\nHimmet Arslan",
    receiver: "Mustafa Yasin Veziroglu",
    from: "Izmit (Kocaeli) / Gebze",
    fromCity: "Gebze",
    to: "Antalya / Kepez",
    toCity: "Antalya",
    amount: 500,
    departureDate: "14.02.2026",
    departureTime: "13:35",
    arrivalDate: "15.02.2026",
    arrivalTime: "00:15",
    plate: "35 PK 324",
  },
  {
    id: "10",
    status: "giden",
    trackingNo: "203 513 151",
    pieces: 1,
    sender: "Hediye Kilic",
    receiver: "Sinan Soylemez",
    from: "Izmit (Kocaeli) / Gebze",
    fromCity: "Gebze",
    to: "Izmir / Aliaga",
    toCity: "Aliaga",
    amount: 400,
    departureDate: "14.02.2026",
    departureTime: "12:00",
    arrivalDate: "14.02.2026",
    arrivalTime: "18:50",
    plate: "77 AB 305",
  },
]
