export interface Sube {
  sube: string
  il: string
  ilce: string
  firma: string
}

export const subeler: Sube[] = [
  { sube: "Adapazari", il: "Sakarya", ilce: "Adapazari", firma: "1787 Kargo" },
  { sube: "Afyon", il: "Afyon", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Aksaray", il: "Aksaray", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Alanya", il: "Antalya", ilce: "Alanya", firma: "1787 Kargo" },
  { sube: "Aliaga", il: "Izmir", ilce: "Aliaga", firma: "1787 Kargo" },
  { sube: "Alibeykoy", il: "Istanbul", ilce: "Eyupsultan", firma: "1787 Kargo" },
  { sube: "Ankara", il: "Ankara", ilce: "Yenimahalle", firma: "1787 Kargo" },
  { sube: "Antalya", il: "Antalya", ilce: "Kepez", firma: "1787 Kargo" },
  { sube: "Aydin", il: "Aydin", ilce: "Efeler", firma: "1787 Kargo" },
  { sube: "Ayvalik", il: "Balikesir", ilce: "Ayvalik", firma: "1787 Kargo" },
  { sube: "Balikesir", il: "Balikesir", ilce: "Karesi", firma: "1787 Kargo" },
  { sube: "Bandirma", il: "Balikesir", ilce: "Bandirma", firma: "1787 Kargo" },
  { sube: "Bergama", il: "Izmir", ilce: "Bergama", firma: "1787 Kargo" },
  { sube: "Biga", il: "Canakkale", ilce: "Biga", firma: "1787 Kargo" },
  { sube: "Bilecik", il: "Bilecik", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Bodrum", il: "Mugla", ilce: "Bodrum", firma: "1787 Kargo" },
  { sube: "Bolu", il: "Bolu", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Burdur", il: "Burdur", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Bursa", il: "Bursa", ilce: "Osmangazi", firma: "1787 Kargo" },
  { sube: "Canakkale", il: "Canakkale", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Cankiri", il: "Cankiri", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Corum", il: "Corum", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Dalaman", il: "Mugla", ilce: "Dalaman", firma: "1787 Kargo" },
  { sube: "Denizli", il: "Denizli", ilce: "Merkezefendi", firma: "1787 Kargo" },
  { sube: "Duzce", il: "Duzce", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Edirne", il: "Edirne", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Elazig", il: "Elazig", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Eskisehir", il: "Eskisehir", ilce: "Odunpazari", firma: "1787 Kargo" },
  { sube: "Fethiye", il: "Mugla", ilce: "Fethiye", firma: "1787 Kargo" },
  { sube: "Gaziantep", il: "Gaziantep", ilce: "Sahinbey", firma: "1787 Kargo" },
  { sube: "Gebze", il: "Kocaeli", ilce: "Gebze", firma: "1787 Kargo" },
  { sube: "Giresun", il: "Giresun", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Hatay", il: "Hatay", ilce: "Antakya", firma: "1787 Kargo" },
  { sube: "Isparta", il: "Isparta", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Istanbul Anadolu", il: "Istanbul", ilce: "Kadikoy", firma: "1787 Kargo" },
  { sube: "Istanbul Avrupa", il: "Istanbul", ilce: "Bayrampasa", firma: "1787 Kargo" },
  { sube: "Izmir", il: "Izmir", ilce: "Konak", firma: "1787 Kargo" },
  { sube: "Izmit", il: "Kocaeli", ilce: "Izmit", firma: "1787 Kargo" },
  { sube: "Kahramanmaras", il: "Kahramanmaras", ilce: "Dulkadiroglu", firma: "1787 Kargo" },
  { sube: "Karabuk", il: "Karabuk", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Karaman", il: "Karaman", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Kastamonu", il: "Kastamonu", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Kayseri", il: "Kayseri", ilce: "Melikgazi", firma: "1787 Kargo" },
  { sube: "Kirikkale", il: "Kirikkale", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Kirklareli", il: "Kirklareli", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Kirsehir", il: "Kirsehir", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Konya", il: "Konya", ilce: "Selcuklu", firma: "1787 Kargo" },
  { sube: "Kutahya", il: "Kutahya", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Luleburgaz", il: "Kirklareli", ilce: "Luleburgaz", firma: "1787 Kargo" },
  { sube: "Malatya", il: "Malatya", ilce: "Yesilyurt", firma: "1787 Kargo" },
  { sube: "Manisa", il: "Manisa", ilce: "Yunusemre", firma: "1787 Kargo" },
  { sube: "Marmaris", il: "Mugla", ilce: "Marmaris", firma: "1787 Kargo" },
  { sube: "Mersin", il: "Mersin", ilce: "Yenisehir", firma: "1787 Kargo" },
  { sube: "Mugla", il: "Mugla", ilce: "Mentese", firma: "1787 Kargo" },
  { sube: "Nevsehir", il: "Nevsehir", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Nigde", il: "Nigde", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Ordu", il: "Ordu", ilce: "Altinordu", firma: "1787 Kargo" },
  { sube: "Osmaniye", il: "Osmaniye", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Rize", il: "Rize", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Sakarya", il: "Sakarya", ilce: "Serdivan", firma: "1787 Kargo" },
  { sube: "Samsun", il: "Samsun", ilce: "Ilkadim", firma: "1787 Kargo" },
  { sube: "Sinop", il: "Sinop", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Sivas", il: "Sivas", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Tekirdag", il: "Tekirdag", ilce: "Suleymanpasa", firma: "1787 Kargo" },
  { sube: "Tokat", il: "Tokat", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Trabzon", il: "Trabzon", ilce: "Ortahisar", firma: "1787 Kargo" },
  { sube: "Usak", il: "Usak", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Yalova", il: "Yalova", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Yozgat", il: "Yozgat", ilce: "Merkez", firma: "1787 Kargo" },
  { sube: "Zonguldak", il: "Zonguldak", ilce: "Merkez", firma: "1787 Kargo" },
]
